#!/usr/bin/env bash
# ==============================================================================
# Decision Model & Heavyweight LLM Benchmark - Automated Setup Script
# ==============================================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=============================================================================="
echo "🏛️  SETUP BENCHMARK MODEL DECISION & FOUNDATION LLM INDONESIA"
echo "=============================================================================="
echo "Repository: https://github.com/tuwiliyt/decisionmodelbench"
echo "Target OS : Ubuntu 20.04/22.04/24.04 / Debian / Google Colab"
echo "GPU Ready : NVIDIA Tesla T4 / A10G / L4 / A100 / RTX 3090/4090"
echo "=============================================================================="
echo ""

# 1. Hardware & GPU Detection
echo "🔍 [1/6] Memeriksa Perangkat Keras & GPU..."
if command -v nvidia-smi &> /dev/null; then
    GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -n 1)
    GPU_VRAM=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader | head -n 1)
    echo "✓ GPU Terdeteksi: $GPU_NAME ($GPU_VRAM)"
else
    echo "⚠️  NVIDIA GPU tidak terdeteksi via nvidia-smi. Pengujian model kelas berat akan berjalan di CPU (sangat lambat)."
fi

# 2. Python Environment Check
echo ""
echo "🐍 [2/6] Memeriksa Versi Python..."
if command -v python3 &> /dev/null; then
    PY_VER=$(python3 --version)
    echo "✓ $PY_VER terpasang."
else
    echo "❌ Python 3 tidak ditemukan. Harap pasang Python 3.10 atau lebih baru."
    exit 1
fi

# 3. Interactive Jev API Key Configuration
echo ""
echo "=============================================================================="
echo "🔑 [3/6] KONFIGURASI API KEY TYPESAFE JEV"
echo "=============================================================================="
echo "Sistem mendukung integrasi cloud SaaS TypeSafe Jev API (https://typesafe.ai)."
echo "Jika Anda memiliki API Key TypeSafe Jev, masukkan di bawah ini."
echo "Tekan [Enter] untuk melewati jika hanya ingin menggunakan model lokal GPU (Laya, OpenJev, Kev)."
echo "------------------------------------------------------------------------------"
read -r -p "Masukkan TypeSafe Jev API Key: " INPUT_JEV_KEY

if [ -n "$INPUT_JEV_KEY" ]; then
    # Write to .env
    cat <<EOF > .env
# Auto-generated by setup.sh
JEV_API_KEY="$INPUT_JEV_KEY"
JEV_ENDPOINT="https://api.typesafe.ai/v1/systemone"
MODELS_DIR="/root/models"
PORT=7860
EOF
    echo "✓ API Key berhasil disimpan ke file .env!"
else
    if [ ! -f .env ]; then
        cp .env.example .env 2>/dev/null || cat <<EOF > .env
JEV_API_KEY=""
JEV_ENDPOINT="https://api.typesafe.ai/v1/systemone"
MODELS_DIR="/root/models"
PORT=7860
EOF
    fi
    echo "ℹ️  Jev API Key dilewati. Seluruh model lokal (Laya, OpenJev, Kev) tetap aktif 100%."
fi

# 4. Install Core Python Dependencies
echo ""
echo "📦 [4/6] Memasang Dependensi Python (pip install)..."
pip install --upgrade pip
pip install -r requirements.txt

# Install Kev framework if not already installed
if ! python3 -c "import kev" &> /dev/null; then
    echo "Mengunduh & memasang pustaka Kev dari GitHub..."
    pip install git+https://github.com/jaredpalmer/kev.git || echo "⚠️ Pemasangan kev via git gagal, lewati."
else
    echo "✓ Pustaka Kev sudah terpasang."
fi

# Check llama-cpp-python CUDA acceleration
if ! python3 -c "import llama_cpp" &> /dev/null; then
    echo "Memasang llama-cpp-python dengan akselerasi CUDA GPU..."
    CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python --no-cache-dir || pip install llama-cpp-python
else
    echo "✓ llama-cpp-python sudah terpasang."
fi

# 5. Download Heavyweight LLM Models (Optional Interactive)
echo ""
echo "=============================================================================="
echo "📥 [5/6] UNDUHAN MODEL LLM KELAS BERAT (GGUF 4-BIT QUANTIZED)"
echo "=============================================================================="
echo "Pilih opsi pengunduhan model kelas berat:"
echo "  1) Unduh Lengkap (Sahabat-AI 8B, Qwen 2.5 7B, Gemma 2 9B, Gemma 2 2B) ~16 GB"
echo "  2) Unduh Cepat / Quick Test (Sahabat-AI 8B + Gemma 2 2B) ~6.2 GB"
echo "  3) Lewati sekarang (Unduh nanti dengan: python3 download_models.py)"
echo "------------------------------------------------------------------------------"
read -r -p "Pilihan Anda [1/2/3, default: 2]: " DOWNLOAD_CHOICE
DOWNLOAD_CHOICE=${DOWNLOAD_CHOICE:-2}

case "$DOWNLOAD_CHOICE" in
    1)
        echo "Mengunduh seluruh model kelas berat..."
        python3 download_models.py --models all
        ;;
    2)
        echo "Mengunduh model cepat (Sahabat-AI 8B + Gemma 2 2B)..."
        python3 download_models.py --models quick
        ;;
    *)
        echo "Unduhan model dilewati. Anda dapat menjalankannya nanti dengan: python3 download_models.py"
        ;;
esac

# 6. Generate Dashboards
echo ""
echo "🎨 [6/6] Mengompilasi Antarmuka Web Dashboard..."
python3 generate_dashboard.py
python3 generate_heavyweight_dashboard.py

echo ""
echo "=============================================================================="
echo "🎉 INSTALASI SELESAI & SISTEM SIAP DIGUNAKAN!"
echo "=============================================================================="
echo ""
echo "PILIHAN CARA MENJALANKAN PENGUJIAN:"
echo ""
echo "1. MODE HEADLESS / CLI (Terminal Tanpa Browser):"
echo "   $ python3 benchmark_headless.py --compare --preset marunda"
echo "   $ python3 benchmark_headless.py --all-presets"
echo "   $ python3 benchmark_headless.py --matrix"
echo "   $ python3 benchmark_headless.py --interactive"
echo ""
echo "2. MODE WEB DASHBOARD (Antarmuka Visual & nvtop Monitor):"
echo "   $ python3 -m uvicorn app_server:app --host 0.0.0.0 --port 7860"
echo "   Buka browser di: http://localhost:7860/heavyweight"
echo ""
echo "3. MODE PUBLIK (Cloudflare Tunnel):"
echo "   $ cloudflared tunnel --url http://localhost:7860"
echo "=============================================================================="
